"""
heuristic_tagger.py
--------------------
Classifies a git commit as AI-generated or Human-authored using heuristics
applied to the commit message and author metadata.

Heuristics checked:
  1. Co-authored-by trailer references a known AI agent (Copilot, Codex, Claude,
     ChatGPT, Devin, Cursor …).
  2. The commit message body contains AI-attribution phrases (e.g. "Generated by
     Codex", "Co-authored by GitHub Copilot").
  3. The committer / author e-mail contains bot indicators.
  4. The author name matches a known AI-agent name.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Optional

# ---------------------------------------------------------------------------
# Public tag values
# ---------------------------------------------------------------------------
TAG_AI    = "AI"
TAG_HUMAN = "Human"

# ---------------------------------------------------------------------------
# Heuristic keyword lists
# ---------------------------------------------------------------------------

# Patterns matched against the *full* commit message (case-insensitive)
_MESSAGE_PATTERNS: list[re.Pattern] = [
    re.compile(r"generated\s+by\s+(?:openai\s+)?codex", re.IGNORECASE),
    re.compile(r"co\s*-?\s*authored\s*-?\s*by\s*:?\s*[^\n]*?\b(?:ai|llm|gpt|claude|copilot|codex|cursor|chatgpt|devin)\b", re.IGNORECASE),
    re.compile(r"\bgenerated\s+by\s+(?:ai|llm|gpt|claude|copilot|codex|cursor)\b", re.IGNORECASE),
    re.compile(r"\bauto\s*-?\s*generated\s+by\s+(?:ai|llm|gpt|claude|copilot|codex|cursor)\b", re.IGNORECASE),
    re.compile(r"\bwith\s+the\s+help\s+of\s+(?:ai|chatgpt|gpt|copilot|claude|codex|cursor)\b", re.IGNORECASE),
]

# Matched against individual "Co-authored-by:" trailer lines (case-insensitive)
_COAUTHOR_PATTERNS: list[re.Pattern] = [
    re.compile(r"copilot", re.IGNORECASE),
    re.compile(r"codex", re.IGNORECASE),
    re.compile(r"openai", re.IGNORECASE),
    re.compile(r"github-copilot", re.IGNORECASE),
    re.compile(r"\bclaude\b", re.IGNORECASE),
    re.compile(r"\bchatgpt\b", re.IGNORECASE),
    re.compile(r"\bgpt\b", re.IGNORECASE),
    re.compile(r"\bdevin\b", re.IGNORECASE),
    re.compile(r"\bcursor\b", re.IGNORECASE),
    re.compile(r"actions-user", re.IGNORECASE),
]

# Matched against committer / author e-mail address
_EMAIL_PATTERNS: list[re.Pattern] = [
    re.compile(r"copilot", re.IGNORECASE),
    re.compile(r"openai", re.IGNORECASE),
    re.compile(r"noreply\+copilot", re.IGNORECASE),
    re.compile(r"bot@", re.IGNORECASE),
    re.compile(r"\bbot\b", re.IGNORECASE),
]

# Matched against the author *name* field
_AUTHOR_NAME_PATTERNS: list[re.Pattern] = [
    re.compile(r"\bgithub[- ]copilot\b", re.IGNORECASE),
    re.compile(r"\bcopilot\b", re.IGNORECASE),
    re.compile(r"\bdevin\b", re.IGNORECASE),
    re.compile(r"\bchatgpt\b", re.IGNORECASE),
    re.compile(r"\bclaude\b", re.IGNORECASE),
    re.compile(r"\bcursor\b", re.IGNORECASE),
    re.compile(r"\bcodex\b", re.IGNORECASE),
]

# Regex to extract all "Co-authored-by:" trailer lines from a commit message
_COAUTHOR_LINE_RE = re.compile(
    r"^co\s*-?\s*authored\s*-?\s*by\s*:(.+)$",
    re.IGNORECASE | re.MULTILINE,
)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class TagResult:
    """Holds the tagging decision for a single commit."""
    tag: str                        # TAG_AI or TAG_HUMAN
    reasons: list[str] = field(default_factory=list)

    @property
    def is_ai(self) -> bool:
        return self.tag == TAG_AI


# ---------------------------------------------------------------------------
# Core tagging function
# ---------------------------------------------------------------------------

def tag_commit(
    message: str,
    author_name: str = "",
    author_email: str = "",
    committer_name: str = "",
    committer_email: str = "",
) -> TagResult:
    """
    Classify a single commit.

    Parameters
    ----------
    message : str
        The full commit message (subject + body including trailers).
    author_name : str
        Git author name (``git log --format=%aN``).
    author_email : str
        Git author e-mail.
    committer_name : str
        Git committer name.
    committer_email : str
        Git committer e-mail.

    Returns
    -------
    TagResult
        The decision and list of human-readable reasons.
    """
    reasons: list[str] = []

    # ---- 1. Author / committer name ----------------------------------------
    for name in (author_name, committer_name):
        for pat in _AUTHOR_NAME_PATTERNS:
            if pat.search(name.strip()):
                reasons.append(f"Author/committer name matches AI pattern: '{name}'")

    # ---- 2. Author / committer e-mail --------------------------------------
    for email in (author_email, committer_email):
        for pat in _EMAIL_PATTERNS:
            if pat.search(email):
                reasons.append(f"Author/committer e-mail matches AI pattern: '{email}'")

    # ---- 3. Co-authored-by trailers ----------------------------------------
    for trailer_value in _COAUTHOR_LINE_RE.findall(message):
        trailer_value = trailer_value.strip()
        for pat in _COAUTHOR_PATTERNS:
            if pat.search(trailer_value):
                reasons.append(f"Co-authored-by trailer matches AI pattern: '{trailer_value}'")

    # ---- 4. Full message body ----------------------------------------------
    for pat in _MESSAGE_PATTERNS:
        m = pat.search(message)
        if m:
            reasons.append(f"Message body matches AI phrase: '...{m.group(0)}...'")

    # ---- Decision ----------------------------------------------------------
    if reasons:
        # Deduplicate while preserving order
        seen: set[str] = set()
        unique_reasons: list[str] = []
        for r in reasons:
            if r not in seen:
                seen.add(r)
                unique_reasons.append(r)
        return TagResult(tag=TAG_AI, reasons=unique_reasons)

    return TagResult(tag=TAG_HUMAN, reasons=[])


# ---------------------------------------------------------------------------
# Convenience wrapper for GitPython commit objects
# ---------------------------------------------------------------------------

def tag_git_commit(commit) -> TagResult:
    """
    Tag a GitPython ``git.Commit`` object directly.

    Parameters
    ----------
    commit : git.Commit
        Any commit obtained via ``Repo.commit(sha)`` or a traversal.

    Returns
    -------
    TagResult
    """
    message = commit.message or ""
    author_name    = commit.author.name    or ""
    author_email   = commit.author.email   or ""
    committer_name = commit.committer.name  or ""
    committer_email = commit.committer.email or ""

    return tag_commit(
        message=message,
        author_name=author_name,
        author_email=author_email,
        committer_name=committer_name,
        committer_email=committer_email,
    )


# ---------------------------------------------------------------------------
# CLI usage for quick testing
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import sys
    test_messages = [
        "Fix bug in parser\n\nCo-authored-by: GitHub Copilot <copilot@github.com>",
        "Refactor auth module\n\nGenerated by Codex",
        "Add unit tests for api.py",
        "Update README.md\n\nWith the help of ChatGPT",
        "Merge pull request #42 from feature/login",
    ]
    for msg in test_messages:
        result = tag_commit(msg)
        print(f"[{result.tag}] '{msg.splitlines()[0]}'")
        for r in result.reasons:
            print(f"       -> {r}")
